DART9
practical 9


(a)

void main(){
  int x=1;
  if(x==1){
    print("please pay 2000 rupees");
  }else if(x==2){
    print("please pay 3000 rupees");
  }else if(x==3){
    print("please pay 7000 rupees");
  }else{
    print("please pay 2500 rupees");
  }
}

(b)

void main(){
  int x=6;
  if(x==1){
    print("please pay 2000 rupees");
  }else if(x==2){
    print("please pay 3000 rupees");
  }else if(x==3){
    print("please pay 7000 rupees");
  }else{
    print("please pay 2500 rupees");
  }
}

