DART5 
PRACTICAL5

(A)

void main(){
  var c="A";
  
  if (c=="A"||c=="E"||c=="I"||c=="O"||c=="U"||c=="a"||c=="e"||c=="i"||c=="o"||c=="u"){
    print("$c is a vowel");
  }else{
    print("$c is a constant");
  }
}

(b)

void main(){
  var c="D";
  
  if (c=="A"||c=="E"||c=="I"||c=="O"||c=="U"||c=="a"||c=="e"||c=="i"||c=="o"||c=="u"){
    print("$c is a vowel");
  }else{
    print("$c is a constant");
  }
}
