DART 12

void main(){
  
  int x = 9;
  
  switch(x){
      
    case 1: 
      
      print("violet");
      
       case 2: 
      
      print("indigo");
      
      
       case 3: 
      
      print("blue");
      
       case 4: 
      
      print("Green");
      
       case 5: 
      
      print("Yellow");
      
      
       case 6: 
      
      print("orange");
      
       case 7: 
      
      print("Red");
      
    default:
      
      print("invalid input");
  }
  
  
  
}