DART8
practical 8


(a)

void main(){
  int x=15;
  if (x%3==0&&x%5==0){
    print("divisible by both");
  }else if(x%3==0){
    print("divisible by 3");
  }else if(x%5==0){
    print("divisible by 5");
  }else{
    print("it is nither divisible by 3 or 5");
  }    
}


(b)

void main(){
  int x=9;
  if (x%3==0&&x%5==0){
    print("divisible by both");
  }else if(x%3==0){
    print("divisible by 3");
  }else if(x%5==0){
    print("divisible by 5");
  }else{
    print("it is nither divisible by 3 or 5");
  }    
}