DART7
practical 7

(a)

void main(){
  dynamic month=7;
  switch(month){
      case 1:
      print("january has 31 days");
       case 2:
      print("february has 28 days");
       case 3:
      print("march has 31 days");
       case 4:
      print("april has 30 days");
       case 5:
      print("may has 31 days");
       case 6:
      print("june has 30 days");
       case 7:
      print("july has 31 days");
       case 8:
      print("august has 31 days");
       case 9:
      print("september has 30 days");
       case 10:
      print("october has 31 days");
       case 11:
      print("november has 30 days");
       case 12:
      print("december has 31 days");
    default:
      print("invaild month");
  }
}


(b)

void main(){
  dynamic month=13;
  switch(month){
      case 1:
      print("january has 31 days");
       case 2:
      print("february has 28 days");
       case 3:
      print("march has 31 days");
       case 4:
      print("april has 30 days");
       case 5:
      print("may has 31 days");
       case 6:
      print("june has 30 days");
       case 7:
      print("july has 31 days");
       case 8:
      print("august has 31 days");
       case 9:
      print("september has 30 days");
       case 10:
      print("october has 31 days");
       case 11:
      print("november has 30 days");
       case 12:
      print("december has 31 days");
    default:
      print("invaild month");
  }
}