DART6
practical6

(a)

void main(){
  int x=4;
  switch(x){
    case 0:
      print("zero");
    case 1:
      print("one");
    case 2:
      print("two");
    case 3:
      print("three");
    case 4:
      print("four");
    case 5:
      print("five");
    default:
      print("$x is greater than 5");
  }
}

(b)

void main(){
  int x=6;
  switch(x){
    case 0:
      print("zero");
    case 1:
      print("one");
    case 2:
      print("two");
    case 3:
      print("three");
    case 4:
      print("four");
    case 5:
      print("five");
    default:
      print("$x is greater than 5");
  }
}