//Program 20
void main() {
int  square = 0;
int cube = 0;
  for (int i = 20; i <= 70; i++) {
    
    if (i % 2 != 0){
      
      square = i * i;
      
    print("square of odd numbers from the range of 20 to 70 is $i: $square \n\n");
      
      
}

    else if (i % 2 == 0) {
      
      cube = i * i * i;

    
    print("cube of even numbers from the range of 20 to 70 is $i: $cube\n\n");
    
    
    }    
    
    
    
  }
    
    
  
  
}


